[package]
name = "shift-lib-rs-math"
version = "0.1.0"
edition = "2018"
license = "CC0-1.0"
repository = ""
keywords = ["competitive"]
publish = false

[lib]
name = "shift_math"

[dependencies]
rustc-hash = "=1.1.0"
